
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class BOOKING
{

    public int id { get; set; }

    public int MaDOANDL { get; set; }

    public int MaKH { get; set; }

    public int MaTour { get; set; }

    public int Siso { get; set; }

    public int GiaTour { get; set; }

}

}
