
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class Booking
{

    public int id { get; set; }

    public Nullable<int> MaDOANDL { get; set; }

    public Nullable<int> MaKH { get; set; }

    public Nullable<int> MaTour { get; set; }

    public Nullable<int> Siso { get; set; }

    public Nullable<int> GiaTour { get; set; }

}

}
