//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHIPHI
    {
        public int ChiPhi_ID { get; set; }
        public Nullable<int> MaDOANDL { get; set; }
        public string ChiPhi_TongCong { get; set; }
    }
}
