//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET
    {
        public int IDCHITIET { get; set; }
        public Nullable<int> MaTour { get; set; }
        public Nullable<int> MaDiaDiem { get; set; }
        public Nullable<int> thutu { get; set; }
    }
}
