
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class DOANDL
{

    public int MaDOANDL { get; set; }

    public System.DateTime NgayKhoiHanh { get; set; }

    public System.DateTime NgayKetThuc { get; set; }

    public int MaNV { get; set; }

    public int MaTour { get; set; }

    public string TenDoan { get; set; }

    public Nullable<int> Soluong { get; set; }

    public Nullable<double> ChiPhi { get; set; }

    public Nullable<double> TongTien { get; set; }

}

}
