
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class DOANDL
{

    public int MaDOANDL { get; set; }

    public Nullable<System.DateTime> NgayKhoiHanh { get; set; }

    public Nullable<System.DateTime> NgayKetThuc { get; set; }

    public Nullable<int> MaKH { get; set; }

    public Nullable<int> MaNV { get; set; }

    public Nullable<int> MaTour { get; set; }

    public string TenDoan { get; set; }

    public Nullable<int> Trans_ID { get; set; }

    public Nullable<int> Accom_ID { get; set; }

}

}
