
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class GIA
{

    public int IDGIATOUR { get; set; }

    public Nullable<System.DateTime> TGBatDau { get; set; }

    public Nullable<System.DateTime> TGKetThuc { get; set; }

    public Nullable<double> ThanhTien { get; set; }

    public int MaTour { get; set; }

}

}
