
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class KHACHHANG
{

    public int MaKH { get; set; }

    public string TenKH { get; set; }

    public Nullable<System.DateTime> KH_NgaySinh { get; set; }

    public string KH_DiaChi { get; set; }

    public string KH_SoDienThoai { get; set; }

    public string KH_GioiTinh { get; set; }

    public string KH_email { get; set; }

    public string KH_CMND { get; set; }

}

}
