//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIHINHDULICH
    {
        public int MaLoaiHinh { get; set; }
        public string TenLoaiHinh { get; set; }
        public string LH_MoTa { get; set; }
    }
}
