
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tour.DAO
{

using System;
    using System.Collections.Generic;
    
public partial class NHANVIEN
{

    public int MaNV { get; set; }

    public string TenNV { get; set; }

    public Nullable<System.DateTime> NV_NgaySinh { get; set; }

    public string NV_SoDienThoai { get; set; }

    public string NV_NhiemVu { get; set; }

}

}
