//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOURDULICH
    {
        public int MaTour { get; set; }
        public string TenTour { get; set; }
        public string DacDiem { get; set; }
        public Nullable<int> IDGiaTour { get; set; }
        public Nullable<int> MaDOANDL { get; set; }
        public Nullable<int> MaLoaiHinh { get; set; }
        public Nullable<int> MaDiaDiem { get; set; }
    }
}
